dist: xenial
language: python

python:
  - "3.6"

install:
- python setup.py -q install

script:
  - echo "Running Tests ..."
  - pytest -v --cov
  - flake8

# after_success:
  # - python setup.py sdist bdist_wheel
  # - twine upload dist/*

notifications:
  email:
    recipients:
      - mukesh@mukeshmithrakumar.com
    on_success: never
    on_failure: always
